### PR TITLE
Use GNUInstallDirs for install paths

### PR DESCRIPTION
**Pull request by tripzero**
libdir might have different name than "lib" (ie, lib32, lib64, etc).  Use cmake GNU standards by default which operating systems know to change to match their configuration.

This patch also gives each so a version string.

### CODE REVIEW

**Comment by paigeale** [comment]
Thank you Kevron. I will port this change into our closed source system to go through the proper testing. I will provide feedback if anything goes wrong.

**Comment by tjaalton** [comment]
thanks for the patch, I gave it a try.. but I don't see it install libigdfcl anywhere, since it drops the line for fcl_dll

**Comment by paigeale** [comment]
The patch was slightly modified to remove ".so" naming convention for we were working on another patch to handle that. Patch to handle GNUInstallDirs will go in tonight

**Comment by tjaalton** [comment]
ok, let me know what the .so patch will be and I'll try that

**Comment by tripzero** [comment]
> thanks for the patch, I gave it a try.. but I don't see it install libigdfcl anywhere, since it drops the line for fcl_dll

Looks like I screwed up the rebase.  That would explain why I no longer see it locally.  @paigeale do you want me to submit without the so rename and with the fcl_dll fix?

**Comment by paigeale** [comment]
.so rename is applied in 3cc1170208f6a0c984e906fc5d531798313d5f40 . GNUInstallDirs going in today

**Comment by tripzero** [comment]
Looks like 0770a37 covers most of this. closing

**Comment by tjaalton** [comment]
it got reverted though, so shouldn't this be reopened now?

**Comment by dvrogozh** [comment]
I also think this one needs to be reopened, but I don't have right to do that. Resolving this issue we need to pay attention at https://github.com/intel/intel-graphics-compiler/issues/82#issuecomment-474952874.

**Comment by dvrogozh** [comment]
Commit https://github.com/intel/intel-graphics-compiler/commit/48660a1afca7056f6099adaa0de43e4089e0c3d7 should fix this issue. @tripzero : can you, please, verify?

**Comment by tripzero** [comment]
> Commit [48660a1](https://github.com/intel/intel-graphics-compiler/commit/48660a1afca7056f6099adaa0de43e4089e0c3d7) should fix this issue. @tripzero : can you, please, verify?

`%files dev
%defattr(-,root,root,-)
/usr/include/igc/cif/CMakeLists.txt
/usr/include/igc/cif/cif/CMakeLists.txt
/usr/include/igc/cif/cif/builtins/builtins_registry.h
/usr/include/igc/cif/cif/builtins/memory/buffer/buffer.h
/usr/include/igc/cif/cif/builtins/memory/buffer/impl/buffer_impl.h
/usr/include/igc/cif/cif/common/cif.h
/usr/include/igc/cif/cif/common/cif_main.h
/usr/include/igc/cif/cif/common/coder.h
/usr/include/igc/cif/cif/common/compatibility.h
/usr/include/igc/cif/cif/common/id.h
/usr/include/igc/cif/cif/common/library_api.h
/usr/include/igc/cif/cif/common/library_handle.h
/usr/include/igc/cif/cif/export/build/binary_version.h
/usr/include/igc/cif/cif/export/cif_impl.h
/usr/include/igc/cif/cif/export/cif_main_impl.h
/usr/include/igc/cif/cif/export/interface_creator.h
/usr/include/igc/cif/cif/export/library_api.h
/usr/include/igc/cif/cif/export/muiltiversion.h
/usr/include/igc/cif/cif/export/pimpl_base.h
/usr/include/igc/cif/cif/export/registry.h
/usr/include/igc/cif/cif/helpers/error.h
/usr/include/igc/cif/cif/helpers/memory.h
/usr/include/igc/cif/cif/import/cif_main.h
/usr/include/igc/cif/cif/import/library_api.h
/usr/include/igc/cif/cif/macros/disable.h
/usr/include/igc/cif/cif/macros/enable.h
/usr/include/igc/cif/cif/os/lin/lin_library_handle.h
/usr/include/igc/cif/cif/os/win/win_library_handle.h
/usr/include/igc/igc.opencl.h
/usr/include/igc/ocl_igc_interface/code_type.h
/usr/include/igc/ocl_igc_interface/fcl_ocl_device_ctx.h
/usr/include/igc/ocl_igc_interface/fcl_ocl_translation_ctx.h
/usr/include/igc/ocl_igc_interface/gt_system_info.h
/usr/include/igc/ocl_igc_interface/igc_features_and_workarounds.h
/usr/include/igc/ocl_igc_interface/igc_ocl_device_ctx.h
/usr/include/igc/ocl_igc_interface/igc_ocl_translation_ctx.h
/usr/include/igc/ocl_igc_interface/impl/fcl_ocl_device_ctx_impl.h
/usr/include/igc/ocl_igc_interface/impl/fcl_ocl_translation_ctx_impl.h
/usr/include/igc/ocl_igc_interface/impl/gt_system_info_impl.h
/usr/include/igc/ocl_igc_interface/impl/igc_features_and_workarounds_impl.h
/usr/include/igc/ocl_igc_interface/impl/igc_ocl_device_ctx_impl.h
/usr/include/igc/ocl_igc_interface/impl/igc_ocl_translation_ctx_impl.h
/usr/include/igc/ocl_igc_interface/impl/ocl_gen_binary_impl.h
/usr/include/igc/ocl_igc_interface/impl/ocl_translation_output_impl.h
/usr/include/igc/ocl_igc_interface/impl/platform_impl.h
/usr/include/igc/ocl_igc_interface/ocl_gen_binary.h
/usr/include/igc/ocl_igc_interface/ocl_translation_output.h
/usr/include/igc/ocl_igc_interface/platform.h
/usr/include/igc/ocl_igc_interface/platform_helper.h
/usr/include/igc/ocl_igc_shared/device_enqueue/DeviceEnqueueInternalTypes.h
/usr/include/igc/ocl_igc_shared/device_enqueue/device_enqueue_internal_types.h
/usr/include/igc/ocl_igc_shared/executable_format/patch_g10.h
/usr/include/igc/ocl_igc_shared/executable_format/patch_g7.h
/usr/include/igc/ocl_igc_shared/executable_format/patch_g8.h
/usr/include/igc/ocl_igc_shared/executable_format/patch_g9.h
/usr/include/igc/ocl_igc_shared/executable_format/patch_list.h
/usr/include/igc/ocl_igc_shared/executable_format/patch_shared.h
/usr/include/igc/ocl_igc_shared/executable_format/program_debug_data.h
/usr/include/igc/ocl_igc_shared/gtpin/gtpin_driver_common.h
/usr/include/igc/ocl_igc_shared/gtpin/gtpin_ocl_interface.h
/usr/lib64/pkgconfig/igc-opencl.pc`

double "cif" directory, but otherwise fine.

`%files lib
%defattr(-,root,root,-)
/usr/lib/libopencl_clang.so
/usr/lib64/libiga64.so
/usr/lib64/libigc.so
/usr/lib64/libigdfcl.so
`
the libopencl_clang.so symlink is still an issue https://github.com/intel/intel-graphics-compiler/issues/76

Otherwise, ship it!

**Pull request closed without merging**
